# Generated by Django 3.1.12 on 2021-06-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='Picture'),
        ),
    ]
