# Generated by Django 3.1.12 on 2021-06-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0002_auto_20210620_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.TextField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
