# Generated by Django 3.1.12 on 2021-06-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0006_auto_20210622_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='isrented',
            field=models.BooleanField(default=False),
        ),
    ]
