# Generated by Django 3.1.12 on 2021-06-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0008_auto_20210622_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_rent', models.DateField(editable=False)),
                ('end_time_rent', models.DateField(editable=False)),
                ('isreturned', models.BooleanField(default=False)),
                ('return_helper', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrental.reservation')),
            ],
        ),
    ]
